spring:
  output:
    ansi:
      enabled: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write_dates_as_timestamps: false
    default-property-inclusion: non_null
#  application:
#    name:
# 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.large.dao.**
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      tableUnderline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false
    default-fetch-size: 100
    default-statement-timeout: 100
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    local-cache-scope: session
    jdbc-type-for-null: 'null'

pagehelper:
    helperDialect: mysql
    reasonable: true
    pageSizeZero: true
    supportMethodsArguments: true
    params: count=countSql



#  热部署，自动重启
#  devtools:
#      restart:
#        additional-paths:
#          src/main/java/com/xly