server:
  #会话超时时间，原则上要略大于redis session生效时间14
  port: 8081
  servlet:
    context-path: /large
    session:
      timeout: 30ms
  # Tomcat特性相关
  tomcat:
    # 最大连接数
    max-connections: 10000
    # 等待队列长度，默认100队列也做缓冲池用
    accept-count: 100
    #　链接超时时间
    connection-timeout: 5000ms
    # 最大线程数
    max-threads: 400
    # 最小线程空闲数据
    min-spare-threads: 30
    accesslog:
      enabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    # secs
    backgroundProcessorDelay: 30




